const STATS = [
    '', // this is a filler for blank and unused stats
    'HP_BASE', 'HP_BONUS', 'HP_PERC', 'HP_TOTAL',
    'ATK_BASE', 'ATK_BONUS', 'ATK_PERC', 'ATK_TOTAL',
    'DEF_BASE', 'DEF_BONUS', 'DEF_PERC', 'DEF_TOTAL',
    'ELEMENTAL_MASTERY',
    'STAMINA', // this shit is useless
    'CRIT_RATE', 'CRIT_DAMAGE',
    'HEAL_BONUS', 'HEAL_RECEIVED',
    'ENERGY_RECHARGE',
    'COOLDOWN_REDUCTION',
    'POWERFUL_SHIELD',
    'PYRO_DAMAGE', 'PYRO_BONUS', 'PYRO_RESISTANCE',
    'HYDRO_DAMAGE', 'HYDRO_BONUS', 'HYDRO_RESISTANCE',
    'DENDRO_DAMAGE', 'DENDRO_BONUS', 'DENDRO_RESISTANCE',
    'ELECTRO_DAMAGE', 'ELECTRO_BONUS', 'ELECTRO_RESISTANCE',
    'ANEMO_DAMAGE', 'ANEMO_BONUS', 'ANEMO_RESISTANCE',
    'CRYO_DAMAGE', 'CRYO_BONUS', 'CRYO_RESISTANCE',
    'GEO_DAMAGE', 'GEO_BONUS', 'GEO_RESISTANCE',
    'PHYSICAL_DAMAGE', 'PHYSICAL_BONUS', 'PHYSICAL_RESISTANCE',
    'EXTRA_TEXT'
]

export { STATS }